### ISSUE TITLE
Create a sub controller Middle

### ISSUE THREAD

**Issue by kconde2** [iw1-hdka/dogyguard#26]
Cette partie consiste à séparer la logique de code pour les utilisateurs connectés des non connectés :
Voici les grandes lignes à suivre :
- [ ] créer un dossier `Middle` dans le dossier `Controllers`
- [ ] déplacer tous les contrôleurs associés à la gestion des utilisateurs connectés dans ce dossier
- [ ] changer les namespaces
- [ ] créer un préfixe pour ce dossier dans les config `routes.yml`
- [ ] créer un dossier `middle` dans le dossier `templates`
- [ ] déplacer toutes les vues associés aux controllers correspondant dans `templates/middle`
- [ ] changer toutes les routes names en `app_middle_...`

**Comment by vodkhard** [comment]
Il n'existe que le Backend et le Frontend. L'application pour un utilisateur connecté est la même que tous les autres utilisateurs mis à part le fait qu'il puisse éditer son profil. La création d'un `Middle` n'est pas justifié car elle correspond seulement à une partie du Frontend accessible seulement à l'utilisateur connecté (un espace membre)

**Comment by kconde2** [comment]
Je propose ceci pour séparer en finesse la logique des utilisateurs connectés en tant qu'admin et les utilisateurs connectés en tant que clients. On le garde là, si jamais voit qu'il y a une nécessité majeure de le faire on le fait comme ça au moins c'est posé.
